# Site settings
name: Chris-Cardio Personal Training
version: 0.1.1
author: Max Quattromani
email: max@maxquattromani.com
description: ""
baseurl: "/chris-cardio"
url: "http://quattromani.github.io/chris-cardio"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

facebook_title: 'Chris Cardio - Making Workouts Happen'
facebook_description: 'Chris Cardio - Making Workouts Happen'

disqus: maxquattromani

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: false
google_analytics_id: UA-XXXXXXXX-X
jquery_version: 1.9.0

footer: "Chris Schieffer Personal Trainer"
